### ISSUE TITLE
Not working with SSL server (https)

### ISSUE THREAD

**Issue by Baterka** [nhnent/socket.io-client-unity3d#28]
This not working with SSL? I need to have my connection betwen server and client secured

**Comment by ppz0th** [comment]
@Baterka Hello~ I've fixed this issue. please check this [link](https://github.com/nhnent/socket.io-client-unity3d/commit/8f93985f0f37267d2c9d89049ddf262922b5b4b6).

**Comment by Baterka** [comment]
`socket.io => socket.io - https://<IP_OF_MY_SERVER>:3001 got an unknown error: System.Exception: Unknown Error`
Sorry, not fixed... I can connect from browser by this address but not by Unity

**Comment by Baterka** [comment]
Not working. When I connect to HTTPS Socket.IO server (https://domain:2087/) then Unity Plugin trying to connect but crash with "Connection timed out!". Maybe because wss:// is not reachable, what is, because  connection from browser works well.

**Comment by strobert22** [comment]
> 
> 
> @Baterka Hello~ I've fixed this issue. please check this [link](https://github.com/nhnent/socket.io-client-unity3d/commit/8f93985f0f37267d2c9d89049ddf262922b5b4b6).

Thanks thats works for me on browser and standalone player. this must be in the next release!

**Comment by ang713** [comment]
> Not working. When I connect to HTTPS Socket.IO server (https://domain:2087/) then Unity Plugin trying to connect but crash with "Connection timed out!". Maybe because wss:// is not reachable, what is, because connection from browser works well.

Updating websocket-sharp fixed my "Connection timed out!" issue
